"""add host last seen timestamp

Revision ID: 78f4dc26ddf2
Revises: eee6115cf4f2
Create Date: 2026-08-24 20:33:30.047952

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78f4dc26ddf2"
down_revision: str | Sequence[str] | None = "eee6115cf4f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hosts", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hosts", "last_seen_at")
    # ### end Alembic commands ###
