"""add network checks table

Revision ID: eee6115cf4f2
Revises: 769e1408681d
Create Date: 2026-08-24 15:16:44.254672

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eee6115cf4f2"
down_revision: str | Sequence[str] | None = "769e1408681d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "network_checks",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("port BETWEEN 1 AND 65535", name="ck_network_checks_port_range"),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_network_checks_host_checked_at",
        "network_checks",
        ["host_id", "checked_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_network_checks_host_checked_at", table_name="network_checks")
    op.drop_table("network_checks")
    # ### end Alembic commands ###
